### ISSUE TITLE
model file not supported 

### ISSUE THREAD

**Issue by sanjanasri** [Anmol-Singh-Jaggi/Sign-Language-Recognition#4]
I downloaded the file you have shared and pasted in dir /generated/  and when I try to run the code 'python predict_from_file.py /data/generated/output/knn/model-serialized-knn.pkl' I get an error stating model file not supported. Any help would be appreciated. Thank You

Sorry, I tried with python predict_from_file.py svm, It worked, but I got an error '
/home/sanjana/Documents/Python_pgms/Sign-Language-Recognition-master2/Sign-Language-Recognition/data/images/test/O/001.jpg	O
Resizing image to 100...
Done!
Making background black...
Done!
Making skin white...
Done!
Removing arm...
Done!
Drawing contour around white color...
Error while applying image transformation on image path '/home/sanjana/Documents/Python_pgms/Sign-Language-Recognition-master2/Sign-Language-Recognition/data/images/test/O/001.jpg' with the following exception trace:
Traceback (most recent call last):
  File "predict_from_file.py", line 32, in main
    frame = apply_image_transformation(frame)
  File "/home/sanjana/Documents/Python_pgms/Sign-Language-Recognition-master2/Sign-Language-Recognition/common/image_transformation.py", line 171, in apply_image_transformation
    frame, contour_dimensions = draw_contours(frame)
  File "/home/sanjana/Documents/Python_pgms/Sign-Language-Recognition-master2/Sign-Language-Recognition/common/image_transformation.py", line 122, in draw_contours
    frame, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack

/home/sanjana/Documents/Python_pgms/Sign-Language-Recognition-master2/Sign-Language-Recognition/data/images/test/F/001.jpg	F
Resizing image to 100...
Done!
Making background black...
Done!
Making skin white...
Done!
Removing arm...
Done!
Drawing contour around white color...
Error while applying image transformation on image path '/home/sanjana/Documents/Python_pgms/Sign-Language-Recognition-master2/Sign-Language-Recognition/data/images/test/F/001.jpg' with the following exception trace:
Traceback (most recent call last):
  File "predict_from_file.py", line 32, in main
    frame = apply_image_transformation(frame)
  File "/home/sanjana/Documents/Python_pgms/Sign-Language-Recognition-master2/Sign-Language-Recognition/common/image_transformation.py", line 171, in apply_image_transformation
    frame, contour_dimensions = draw_contours(frame)
  File "/home/sanjana/Documents/Python_pgms/Sign-Language-Recognition-master2/Sign-Language-Recognition/common/image_transformation.py", line 122, in draw_contours
    frame, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack

The program completed successfully !!
'

**Comment by Anmol-Singh-Jaggi** [comment]
Hi! What file did you execute? Can you also show me the log file?

**Comment by Anmol-Singh-Jaggi** [comment]
After a **long** wait, I have made significant changes to the codebase:  
 - Updated to Python3.
 - Updated all the dependencies (scipy/numpy/opencv etc.)
 - Locked the dependencies graph using `pipenv`.  
   (This should solve most of the problems faced by new users)
 - Added logging.
 - Added progress bar.
 - Simplified project setup and the Readme.
 - Minor bug fixes. 

Please try it again now; feedback is highly appreciated! :)
